
const $=s=>document.querySelector(s);const state={day:'monday',data:null,startedAt:null};
const store={get:(k,d=null)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v)),del:k=>localStorage.removeItem(k)};
const today=()=>new Date().toISOString().slice(0,10);
const niceDate=d=>new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function init(){state.data=await fetch('data.json?version=v3core').then(r=>r.json()); if('serviceWorker'in navigator) navigator.serviceWorker.register('service-worker.js'); render();}
function workoutKey(day=state.day,date=today()){return `jp.v3.workout.${date}.${day}`}
function historyKey(day=state.day){return `jp.v3.history.${day}`}
function current(){return store.get(workoutKey(), {date:today(),day:state.day,sets:{},notes:'',startedAt:new Date().toISOString(),finishedAt:null})}
function saveCurrent(w){store.set(workoutKey(),w)}
function lastWorkout(day=state.day){return (store.get(historyKey(day),[])||[])[0]}
function setCount(ex){return ex.sets||3}
function setLabels(ex){return Array.from({length:setCount(ex)},(_,i)=>`Set ${i+1}`)}
function getSet(w,exid,i){return (w.sets[exid]&&w.sets[exid][i])||{weight:'',reps:'',done:false}}
function updateSet(exid,i,field,val){const w=current();w.sets[exid]=w.sets[exid]||[];w.sets[exid][i]=w.sets[exid][i]||{weight:'',reps:'',done:false};w.sets[exid][i][field]=field==='done'?!!val:val;saveCurrent(w);updateMetrics();}
function updateNotes(val){const w=current();w.notes=val;saveCurrent(w)}
function volume(w=current()){let v=0;Object.values(w.sets||{}).flat().forEach(s=>{v+=(parseFloat(s.weight)||0)*(parseFloat(s.reps)||0)});return Math.round(v)}
function completedSets(w=current()){return Object.values(w.sets||{}).flat().filter(s=>s&&s.done).length}
function totalSets(day=state.day){return state.data[day].exercises.reduce((a,e)=>a+setCount(e),0)}
function completedExercises(w=current(), day=state.day){return state.data[day].exercises.filter(ex=>(w.sets[ex.id]||[]).some(s=>s&&s.done)).length}
function render(){const day=state.data[state.day];const w=current();document.getElementById('app').innerHTML=`<main class="shell"><section class="hero"><span class="version">Jo's Program • V3.0 Core</span><h1>Jo's Program</h1><p>Professional workout tracking built around strength, lean muscle, consistency, and knee-smart training.</p><div class="top-actions"><button class="btn secondary" onclick="emailWorkout()">📧 Email Today's Workout</button><button class="btn ok" onclick="finishWorkout()">✓ Finish Workout</button></div></section><nav class="days">${Object.entries(state.data).map(([id,d])=>`<button class="daytab ${id===state.day?'active':''}" onclick="selectDay('${id}')"><b>${d.title}</b><br><span>${d.subtitle}</span></button>`).join('')}</nav><section class="grid"><div><div class="panel"><h2>${esc(day.title)}: ${esc(day.subtitle)}</h2><p class="subtitle">${esc(day.focus)}</p><div class="chips"><span class="chip">${completedSets(w)} / ${totalSets()} sets done</span><span class="chip">${volume(w).toLocaleString()} lb volume</span><span class="chip">Autosaved</span></div></div><div class="panel"><h3>Warm-up</h3><ul>${day.warmup.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>${day.exercises.map(ex=>exerciseCard(ex,w)).join('')}<div class="panel"><h3>Daily Notes</h3><textarea class="notes" oninput="updateNotes(this.value)" placeholder="How did the workout feel? Knee notes, energy, adjustments, etc.">${esc(w.notes||'')}</textarea></div><div class="panel"><h3>Cool-down</h3><ul>${day.cooldown.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="sticky-email"><button class="btn big" onclick="emailWorkout()">📧 Email Today's Workout</button></div></div><aside class="side"><div class="panel"><h3>Today</h3><div class="metric-row"><div class="metric"><strong id="mSets">${completedSets(w)}</strong><span class="muted">sets done</span></div><div class="metric"><strong id="mVol">${volume(w).toLocaleString()}</strong><span class="muted">lb volume</span></div><div class="metric"><strong id="mEx">${completedExercises(w)}</strong><span class="muted">exercises</span></div></div><br><button class="btn big ok" onclick="finishWorkout()">✓ Finish Workout</button><br><br><button class="btn big secondary" onclick="emailWorkout()">📧 Email Workout</button></div><div class="panel"><h3>Previous Workouts</h3><div class="history-list">${historyList()}</div></div></aside></section></main><nav class="footer-nav"><button class="active">Workout</button><button onclick="showHistoryPage()">History</button><button onclick="printSummary()">Print/PDF</button></nav>`}
function exerciseCard(ex,w){const last=lastWorkout();const lastSets=last?.sets?.[ex.id]||[];return `<article class="exercise"><div class="ex-head"><div><div class="ex-title">${esc(ex.name)}</div><div class="ex-meta"><span class="badge">${esc(ex.repRange)} reps</span><span class="badge">${setCount(ex)} sets</span><span class="badge">${esc(ex.type)}</span></div>${lastSets.length?`<div class="last">Last workout: ${lastSets.map((s,i)=>`S${i+1} ${s.weight||'-'} × ${s.reps||'-'}`).join(' | ')}</div>`:`<div class="last">No previous workout logged yet.</div>`}</div><button class="btn ghost" onclick="toggleDetails('${ex.id}')">Details</button></div><table class="set-table"><thead><tr><th>Set</th><th>Weight</th><th>Reps</th><th>Done</th></tr></thead><tbody>${setLabels(ex).map((label,i)=>{const s=getSet(w,ex.id,i);return `<tr><td>${label}</td><td><input type="number" inputmode="decimal" placeholder="lb" value="${esc(s.weight)}" onchange="updateSet('${ex.id}',${i},'weight',this.value)"></td><td><input type="number" inputmode="numeric" placeholder="reps" value="${esc(s.reps)}" onchange="updateSet('${ex.id}',${i},'reps',this.value)"></td><td><input type="checkbox" ${s.done?'checked':''} onchange="updateSet('${ex.id}',${i},'done',this.checked)"></td></tr>`}).join('')}</tbody></table><div class="details"><details id="details-${ex.id}"><summary>Coaching cues, mistakes, and alternatives</summary><div class="detail-grid"><div class="smallbox"><h4>Matt's Tip</h4><p class="muted">${esc(ex.tip)}</p></div><div class="smallbox"><h4>Coaching Cues</h4><ul>${ex.cues.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="smallbox"><h4>Common Mistakes</h4><ul>${ex.mistakes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="smallbox"><h4>Alternatives</h4><ul>${ex.alternatives.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div></details></div></article>`}
function toggleDetails(id){const d=document.getElementById(`details-${id}`); if(d)d.open=!d.open}
function selectDay(id){state.day=id;render()}
function updateMetrics(){const w=current();['mSets','mVol','mEx'].forEach(id=>{const el=document.getElementById(id); if(!el)return; if(id==='mSets')el.textContent=completedSets(w); if(id==='mVol')el.textContent=volume(w).toLocaleString(); if(id==='mEx')el.textContent=completedExercises(w);});}
function historyList(){const h=store.get(historyKey(),[])||[]; if(!h.length)return '<p class="muted">No completed workouts yet. Finish a workout to start history.</p>'; return h.slice(0,8).map(x=>`<div class="history-item"><b>${niceDate(x.date)}</b><br><span class="muted">${x.completedSets||0} sets • ${(x.volume||0).toLocaleString()} lb</span></div>`).join('')}
function finishWorkout(){const w=current();w.finishedAt=new Date().toISOString();w.volume=volume(w);w.completedSets=completedSets(w);w.completedExercises=completedExercises(w);let h=store.get(historyKey(),[])||[];h=[w,...h.filter(x=>x.date!==w.date)].slice(0,30);store.set(historyKey(),h);alert(`Great job, Jo! Workout saved.\n\nSets completed: ${w.completedSets}\nVolume: ${w.volume.toLocaleString()} lb`);render()}
function workoutText(){const day=state.data[state.day];const w=current();let lines=[];lines.push(`Jo's Program - ${day.title}: ${day.subtitle}`);lines.push(`Date: ${niceDate(w.date)}`);lines.push(`Volume: ${volume(w).toLocaleString()} lb`);lines.push(`Sets completed: ${completedSets(w)} / ${totalSets()}`);lines.push('');day.exercises.forEach(ex=>{lines.push(ex.name);setLabels(ex).forEach((label,i)=>{const s=getSet(w,ex.id,i);if(s.weight||s.reps||s.done)lines.push(`  ${label}: ${s.weight||'-'} lb x ${s.reps||'-'} reps ${s.done?'[done]':''}`)});lines.push('')});if(w.notes){lines.push('Notes:');lines.push(w.notes)}return lines.join('\n')}
function emailWorkout(){const day=state.data[state.day];const subject=encodeURIComponent(`Jo's Program - ${day.title} ${day.subtitle} - ${today()}`);const body=encodeURIComponent(workoutText());location.href=`mailto:?subject=${subject}&body=${body}`}
function printSummary(){const text=workoutText().replace(/\n/g,'<br>');const win=window.open('','_blank');win.document.write(`<title>Jo's Program Summary</title><body style="font-family:-apple-system,Segoe UI,Arial;padding:24px;line-height:1.5"><h1>Workout Summary</h1><p>${text}</p><script>window.print()</script></body>`);win.document.close()}
function showHistoryPage(){const all=Object.keys(state.data).map(day=>`<h3>${state.data[day].title}</h3>`+(store.get(historyKey(day),[])||[]).slice(0,10).map(w=>`<div class="history-item"><b>${niceDate(w.date)}</b><br>${w.completedSets||0} sets • ${(w.volume||0).toLocaleString()} lb</div>`).join('')||'<p class="muted">No history.</p>').join('');document.getElementById('app').innerHTML=`<main class="shell"><section class="hero"><span class="version">Jo's Program • V3.0 Core</span><h1>History</h1><p>Completed workouts saved on this phone.</p></section><div class="panel">${all}</div></main><nav class="footer-nav"><button onclick="render()">Workout</button><button class="active">History</button><button onclick="printSummary()">Print/PDF</button></nav>`}
window.selectDay=selectDay;window.updateSet=updateSet;window.updateNotes=updateNotes;window.finishWorkout=finishWorkout;window.emailWorkout=emailWorkout;window.printSummary=printSummary;window.showHistoryPage=showHistoryPage;window.toggleDetails=toggleDetails;
init();
